services:
  postgres:
    restart: always
    image: postgres:15-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432 # enables connecting locally via psql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: viterbi_desk
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  pgdata:
    external: true
